
[env]
TERM = "xterm-256color"

[window]
decorations     = "none"
dynamic_padding = false
dynamic_title   = true
opacity         = 1.0
startup_mode    = "Maximized"
title           = "alacritty"

[window.dimensions]
columns = 90
lines   = 28

[window.padding]
x = 12
y = 12

[scrolling]
history = 12000

[font]
builtin_box_drawing = false
size                = 13.0

[font.bold]
family = "source code pro"
style  = "Bold"


[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "source code pro"
style  = "Bold Italic"
#style  = "Italic"

[font.normal]
family = "source code pro"
style  = "semibold"

[font.offset]
x = 0
y = 0

[colors.primary]
background= "#0f111b"
foreground= "#ecf0c1"

[colors.bright]
    black=   "#686f9a"
    red=     "#e33400"
    green=   "#5ccc96"
    yellow=  "#b3a1e6"
    blue=    "#00a3cc"
    magenta= "#f2ce00"
    cyan=    "#7a5ccc"
    white=   "#f0f1ce"

[colors.cursor]
cursor = "CellForeground"
text   = "CellBackground"

[colors.footer_bar]
background = "#C0C5CE"
foreground = "#232323"

[colors.hints.end]
background = "CellBackground"
foreground = "CellForeground"

[colors.hints.start]
background = "CellBackground"
foreground = "CellForeground"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
    black=   "#000000"
    red=     "#e33400"
    green=   "#5ccc96"
    yellow=  "#b3a1e6"
    blue=    "#00a3cc"
    magenta= "#f2ce00"
    cyan=    "#7a5ccc"
    white=   "#686f9a"

[colors.search.focused_match]
background = "CellBackground"
foreground = "CellForeground"

[colors.search.matches]
background = "CellBackground"
foreground = "CellForeground"

[colors.selection]
background = "CellForeground"
text       = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text   = "CellBackground"

[bell]
animation = "EaseOutExpo"
color     = "#C0C5CE"
command   = "None"
duration  = 0

[selection]
save_to_clipboard     = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[cursor]
unfocused_hollow = true
vi_mode_style    = "None"

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key    = "Return"
mods   = "Control|Shift"

[mouse]
hide_when_typing = true

[debug]
highlight_damage   = false
log_level          = "Warn"
persistent_logging = false
print_events       = false
render_timer       = false

#[general]
# alacritty.toml

#live_config_reload = true
